# Generated by Django 5.0.2 on 2024-03-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(blank=True, null=True)),
                ('origin_image', models.ImageField(blank=True, null=True, upload_to='predicts/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='predicts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
