# Generated by Django 5.0.2 on 2024-04-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/predicts/'),
        ),
        migrations.AlterField(
            model_name='predict',
            name='origin_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/predicts/'),
        ),
    ]
